# Generated by Django 3.2.19 on 2023-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(choices=[('2pm', '2pm'), ('3pm', '3pm'), ('4pm', '4pm')], default='3pm'),
        ),
    ]
