# Generated by Django 3.2.19 on 2023-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_reservation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Reservation',
            new_name='reservation',
        ),
    ]
