# Generated by Django 3.2.19 on 2023-11-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231108_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='HowMany',
        ),
    ]
