# Generated by Django 3.2.19 on 2023-11-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_reservation_client_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='image',
            field=models.ImageField(default='add image', upload_to=None),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default='01:01:2024'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(default='what will you be doing?', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.TextField(choices=[('w', 'wedding'), ('e', 'exam'), ('b', 'birthday'), ('w', 'work'), ('u', 'none of the above')], default='undecided', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='Create your Reservation', max_length=200),
        ),
    ]
