# Generated by Django 3.2.19 on 2023-11-11 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remove_reservation_howmany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='place',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=models.TextField(default='its party time', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.CharField(default='somewhere', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='organizer',
            field=models.ForeignKey(default='partyhost', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='UPDATE', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.TextField(choices=[('w', 'wedding'), ('e', 'exam'), ('b', 'birthday'), ('w', 'work'), ('u', 'undecided')], default='undecided', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(choices=[('2pm', '3pm'), ('4pm', '5pm'), ('6pm', '7pm')], default='3pm'),
        ),
    ]
