# Generated by Django 3.2.19 on 2023-11-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231117_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
