# Generated by Django 3.2.19 on 2023-11-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_reservation_time'),
        ('blog', '0006_alter_reservation_organizer'),
    ]

    operations = [
    ]
