# Generated by Django 3.2.19 on 2023-11-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='image',
        ),
    ]
